baseURL = "https://alanhdu.github.io/"
languageCode = "en-us"
title = "Amateur Hour"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "monokai"
    tabWidth = 4

  # See https://github.com/gohugoio/hugo/pull/7435
  # Install Hugo from https://github.com/fastai/hugo/
  [markup.goldmark]
      [markup.goldmark.extensions]
          mathjax = true
      [markup.goldmark.renderer]
          unsafe = true
